// <auto-generated />
using FastServer.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastServer.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250701235034_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("FastServer.Domain.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Lunch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lunches");
                });

            modelBuilder.Entity("FastServer.Domain.Entities.LunchIngredient", b =>
                {
                    b.Property<int>("LunchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LunchId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("LunchIngredients");
                });

            modelBuilder.Entity("FastServer.Domain.Entities.LunchIngredient", b =>
                {
                    b.HasOne("FastServer.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("LunchIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastServer.Domain.Entities.Lunch", "Lunch")
                        .WithMany("LunchIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Lunch");
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Ingredient", b =>
                {
                    b.Navigation("LunchIngredients");
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Lunch", b =>
                {
                    b.Navigation("LunchIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
